# Generated by Django 3.2.4 on 2021-07-02 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cliente', models.CharField(default='0', max_length=17, unique=True, verbose_name='Código cliente')),
                ('pri_nom', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('seg_nom', models.CharField(max_length=30, verbose_name='Segundo Nombre')),
                ('pri_ap', models.CharField(max_length=30, verbose_name='Apelldo Paterno')),
                ('seg_ap', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(choices=[('1', 'Natural'), ('2', 'Empresa'), ('3', 'Taxi')], default='1', max_length=1, verbose_name='Tipo de Cliente')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], default='F', max_length=1, verbose_name='Sexo')),
                ('numero_tarjeta', models.CharField(max_length=17, unique=True, verbose_name='Número de tarjeta')),
                ('tipo_tarjeta', models.CharField(choices=[('1', 'Xpress'), ('2', 'Flota'), ('3', 'Taxi')], default='1', max_length=1, verbose_name='Tipo de tarjeta')),
                ('tipo_doc', models.CharField(blank=True, choices=[('1', 'Boleta'), ('2', 'Factura')], max_length=1, null=True, verbose_name='Tipo de documento ')),
                ('saldo', models.IntegerField(default=0)),
                ('patente', models.CharField(max_length=16, null=True, unique=True, verbose_name='Patente')),
                ('tipo_vehiculo', models.CharField(choices=[('1', 'Auto'), ('2', 'Camioneta'), ('3', 'Camion'), ('4', 'Bus'), ('5', 'Station Wagon')], default='1', max_length=30, verbose_name='Tipo de vehiculo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
                'db_table': 'tarjeta',
            },
        ),
    ]
