# Generated by Django 3.2.4 on 2021-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_xpress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='cod_cliente',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='rut',
            field=models.CharField(default='0', max_length=17, unique=True, verbose_name='RUT'),
        ),
    ]
