# Generated by Django 3.2.4 on 2021-07-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_xpress', '0002_auto_20210703_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='rut',
            field=models.CharField(max_length=17, unique=True, verbose_name='RUT'),
        ),
    ]
