# Generated by Django 3.2.4 on 2021-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_xpress', '0003_alter_tarjeta_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='rut',
            field=models.CharField(max_length=17, verbose_name='RUT'),
        ),
    ]
