# Generated by Django 3.2.4 on 2021-07-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_xpress', '0005_auto_20210704_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='seg_ap',
            field=models.CharField(default=0, max_length=30, verbose_name='Apellido Materno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='seg_nom',
            field=models.CharField(default=0, max_length=30, verbose_name='Segundo Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_doc',
            field=models.CharField(choices=[('1', 'Boleta'), ('2', 'Factura')], default=0, max_length=1, verbose_name='Tipo de documento '),
            preserve_default=False,
        ),
    ]
